<a href="https://colab.research.google.com/github/MaitreePimple/Crypto-Market-Analytics-Pipeline/blob/main/crypto_market_data_script.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import requests
import pandas as pd

url = "https://api.coingecko.com/api/v3/coins/markets"

params = {
    "vs_currency" : "usd",
    "ids" : "bitcoin,ethereum,solana,cardano,dogecoin"
}

headers = {
    "api-key" : "CG-1hWTRmbziAihi68sgvWs5uvj"
}

response = requests.get(
    url,
    params = params,
    headers = headers
)

data = response.json()
df = pd.DataFrame(data)
print(df.head())

         id symbol      name  \
0   bitcoin    btc   Bitcoin
1  ethereum    eth  Ethereum
2    solana    sol    Solana
3  dogecoin   doge  Dogecoin
4   cardano    ada   Cardano

                                               image  current_price  \
0  https://coin-images.coingecko.com/coins/images...   61857.000000
1  https://coin-images.coingecko.com/coins/images...    1663.670000
2  https://coin-images.coingecko.com/coins/images...      66.500000
3  https://coin-images.coingecko.com/coins/images...       0.084452
4  https://coin-images.coingecko.com/coins/images...       0.163870

      market_cap  market_cap_rank  fully_diluted_valuation  total_volume  \
0  1245321024483                1            1245321024483   52917432330
1   200952268606                2             200952268606   27191410941
2    38527874308                7              41806025603    5173066765
3    13073656517               11              14402749103    1392828522
4     6091553517               17               7376744620    1107061614

       high_24h  ...  total_supply    max_supply            ath  \
0  64353.000000  ...  2.003892e+07  2.100000e+07  126080.000000
1   1788.940000  ...  1.206848e+08           NaN    4946.050000
2     70.420000  ...  6.277866e+08           NaN     293.310000
3      0.089932  ...  1.702450e+11           NaN       0.731578
4      0.191529  ...  4.500000e+10  4.500000e+10       3.090000

   ath_change_percentage                  ath_date        atl  \
0              -50.93796  2025-10-06T18:57:42.558Z  67.810000
1              -66.36362  2025-08-24T19:21:03.333Z   0.432979
2              -77.32618  2025-01-19T11:15:27.957Z   0.500801
3              -88.45620  2021-05-08T05:08:23.458Z   0.000087
4              -94.69146  2021-09-02T06:00:10.474Z   0.019253

   atl_change_percentage                  atl_date  \
0            91122.93762  2013-07-06T00:00:00.000Z
1           384138.59219  2015-10-20T00:00:00.000Z
2            13179.72453  2020-05-11T19:35:23.449Z
3            97078.66746  2015-05-06T00:00:00.000Z
4              751.15006  2020-03-13T02:22:55.044Z

                                                 roi              last_updated
0                                               None  2026-06-05T13:39:44.631Z
1  {'times': 34.91077230557637, 'currency': 'btc'...  2026-06-05T13:39:44.067Z
2                                               None  2026-06-05T13:39:44.639Z
3                                               None  2026-06-05T13:39:44.805Z
4                                               None  2026-06-05T13:39:28.714Z

[5 rows x 26 columns]

In [ ]:
df.head()

,id,symbol,name,image,current_price,market_cap,market_cap_rank,fully_diluted_valuation,total_volume,high_24h,...,total_supply,max_supply,ath,ath_change_percentage,ath_date,atl,atl_change_percentage,atl_date,roi,last_updated
0,bitcoin,btc,Bitcoin,https://coin-images.coingecko.com/coins/images...,61857.000000,1245321024483,1,1245321024483,52917432330,64353.000000,...,2.003892e+07,2.100000e+07,126080.000000,-50.93796,2025-10-06T18:57:42.558Z,67.810000,91122.93762,2013-07-06T00:00:00.000Z,None,2026-06-05T13:39:44.631Z
1,ethereum,eth,Ethereum,https://coin-images.coingecko.com/coins/images...,1663.670000,200952268606,2,200952268606,27191410941,1788.940000,...,1.206848e+08,NaN,4946.050000,-66.36362,2025-08-24T19:21:03.333Z,0.432979,384138.59219,2015-10-20T00:00:00.000Z,"{'times': 34.91077230557637, 'currency': 'btc'...",2026-06-05T13:39:44.067Z
2,solana,sol,Solana,https://coin-images.coingecko.com/coins/images...,66.500000,38527874308,7,41806025603,5173066765,70.420000,...,6.277866e+08,NaN,293.310000,-77.32618,2025-01-19T11:15:27.957Z,0.500801,13179.72453,2020-05-11T19:35:23.449Z,None,2026-06-05T13:39:44.639Z
3,dogecoin,doge,Dogecoin,https://coin-images.coingecko.com/coins/images...,0.084452,13073656517,11,14402749103,1392828522,0.089932,...,1.702450e+11,NaN,0.731578,-88.45620,2021-05-08T05:08:23.458Z,0.000087,97078.66746,2015-05-06T00:00:00.000Z,None,2026-06-05T13:39:44.805Z
4,cardano,ada,Cardano,https://coin-images.coingecko.com/coins/images...,0.163870,6091553517,17,7376744620,1107061614,0.191529,...,4.500000e+10,4.500000e+10,3.090000,-94.69146,2021-09-02T06:00:10.474Z,0.019253,751.15006,2020-03-13T02:22:55.044Z,None,2026-06-05T13:39:28.714Z

In [ ]:
df.columns.tolist()

['id',
 'symbol',
 'name',
 'image',
 'current_price',
 'market_cap',
 'market_cap_rank',
 'fully_diluted_valuation',
 'total_volume',
 'high_24h',
 'low_24h',
 'price_change_24h',
 'price_change_percentage_24h',
 'market_cap_change_24h',
 'market_cap_change_percentage_24h',
 'circulating_supply',
 'total_supply',
 'max_supply',
 'ath',
 'ath_change_percentage',
 'ath_date',
 'atl',
 'atl_change_percentage',
 'atl_date',
 'roi',
 'last_updated']

In [ ]:
crypto_df = df[
    ['name','symbol','current_price','total_volume','price_change_percentage_24h']
]
crypto_df.head()

       name symbol  current_price  total_volume  price_change_percentage_24h
0   Bitcoin    btc   61857.000000   52917432330                     -3.32946
1  Ethereum    eth    1663.670000   27191410941                     -6.69371
2    Solana    sol      66.500000    5173066765                     -5.11144
3  Dogecoin   doge       0.084452    1392828522                     -4.91986
4   Cardano    ada       0.163870    1107061614                    -13.45931

In [ ]:
from datetime import datetime
crypto_df["timestamp"] = datetime.now()
crypto_df.head()

/tmp/ipykernel_4150/2571543621.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  crypto_df["timestamp"] = datetime.now()

,name,symbol,current_price,total_volume,price_change_percentage_24h,timestamp
0,Bitcoin,btc,61857.000000,52917432330,-3.32946,2026-06-05 13:44:48.718556
1,Ethereum,eth,1663.670000,27191410941,-6.69371,2026-06-05 13:44:48.718556
2,Solana,sol,66.500000,5173066765,-5.11144,2026-06-05 13:44:48.718556
3,Dogecoin,doge,0.084452,1392828522,-4.91986,2026-06-05 13:44:48.718556
4,Cardano,ada,0.163870,1107061614,-13.45931,2026-06-05 13:44:48.718556

In [ ]:
crypto_df.to_csv(
    "crypto_data.csv",
    index=False
    )
print("csv saved")

csv saved

In [ ]:
df.shape

(5, 26)

In [ ]:
df.columns.tolist()

['id',
 'symbol',
 'name',
 'image',
 'current_price',
 'market_cap',
 'market_cap_rank',
 'fully_diluted_valuation',
 'total_volume',
 'high_24h',
 'low_24h',
 'price_change_24h',
 'price_change_percentage_24h',
 'market_cap_change_24h',
 'market_cap_change_percentage_24h',
 'circulating_supply',
 'total_supply',
 'max_supply',
 'ath',
 'ath_change_percentage',
 'ath_date',
 'atl',
 'atl_change_percentage',
 'atl_date',
 'roi',
 'last_updated']

In [ ]:
crypto_df = df[
    [
        "name",
        "symbol",
        "current_price",
        "market_cap",
        "market_cap_rank",
        "total_volume",
        "high_24h",
        "low_24h",
        "price_change_percentage_24h"
    ]
]

crypto_df.head()

,name,symbol,current_price,market_cap,market_cap_rank,total_volume,high_24h,low_24h,price_change_percentage_24h
0,Bitcoin,btc,61857.000000,1245321024483,1,52917432330,64353.000000,61394.000000,-3.32946
1,Ethereum,eth,1663.670000,200952268606,2,27191410941,1788.940000,1638.170000,-6.69371
2,Solana,sol,66.500000,38527874308,7,5173066765,70.420000,64.190000,-5.11144
3,Dogecoin,doge,0.084452,13073656517,11,1392828522,0.089932,0.082536,-4.91986
4,Cardano,ada,0.163870,6091553517,17,1107061614,0.191529,0.158433,-13.45931

In [ ]:
from datetime import datetime

crypto_df["timestamp"] = datetime.now()

crypto_df.head()

/tmp/ipykernel_4150/2032605357.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  crypto_df["timestamp"] = datetime.now()

,name,symbol,current_price,market_cap,market_cap_rank,total_volume,high_24h,low_24h,price_change_percentage_24h,timestamp
0,Bitcoin,btc,61857.000000,1245321024483,1,52917432330,64353.000000,61394.000000,-3.32946,2026-06-05 13:54:14.941232
1,Ethereum,eth,1663.670000,200952268606,2,27191410941,1788.940000,1638.170000,-6.69371,2026-06-05 13:54:14.941232
2,Solana,sol,66.500000,38527874308,7,5173066765,70.420000,64.190000,-5.11144,2026-06-05 13:54:14.941232
3,Dogecoin,doge,0.084452,13073656517,11,1392828522,0.089932,0.082536,-4.91986,2026-06-05 13:54:14.941232
4,Cardano,ada,0.163870,6091553517,17,1107061614,0.191529,0.158433,-13.45931,2026-06-05 13:54:14.941232

In [ ]:
crypto_df.shape

(5, 10)

In [ ]:
crypto_df.to_csv(
    "crypto_market_data.csv",
    index=False
)

print("CSV Saved Successfully")

CSV Saved Successfully

In [ ]:
from google.colab import files

files.download("crypto_market_data.csv")